apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: poc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "s3-storage" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: s3-pv # Name of your PV