# https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/values.yaml
# https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/Chart.yaml
# https://github.com/aws/eks-charts/blob/master/stable/aws-cloudwatch-metrics/Chart.yaml
# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/Chart.yaml
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml
# https://github.com/bitnami/charts/blob/main/bitnami/external-dns/Chart.yaml
image:
  repository: public.ecr.aws/aws-observability/aws-for-fluent-bit
  tag: 2.32.2.20240516
  pullPolicy: IfNotPresent

imagePullSecrets: []

podSecurityContext: {}
containerSecurityContext: {}
allowPrivilegeEscalation: false
capabilities: 
  drop:
  - ALL

service:
  parsersFiles:
    - /fluent-bit/parsers/parsers.conf
  storage.path:               /var/log/
  storage.sync:               normal
  storage.checksum:           off
  storage.backlog.mem_limit:  5M
  
input:
  enabled: true
  tag: "kube.app.*"
  path: "/var/log/containers/*.log"
  db: "/var/log/flb_kube.db"
  parser: docker
  dockerMode: "On"
  memBufLimit: 5MB
  skipLongLines: "On"
  refreshInterval: 10
  extraInputs: >
    exclude_path   /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
additionalInputs: |
  [INPUT]
      Name              tail
      tag               host.messages
      path              /var/log/messages
      db                /var/log/flb_messages.db
      parser            syslog
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Refresh_Interval  10
      Read_from_Head    true
  [INPUT]
      Name                tail
      Tag                 host.dmesg
      Path                /var/log/dmesg
      Key                 message
      DB                  /var/log/flb_dmesg.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      true
  [INPUT]
      Name                tail
      Tag                 host.secure
      Path                /var/log/secure
      Parser              syslog
      DB                  /var/log/flb_secure.db
      Mem_Buf_Limit       5MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Read_from_Head      true
  [INPUT]
      Name                systemd
      Tag                 dataplane.systemd.*
      Systemd_Filter      _SYSTEMD_UNIT=containerd.service
      Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
      DB                  /var/log/systemd.db
      Path                /var/log/journal
      Read_From_Tail      true

  [INPUT]
      Name                tail
      Tag                 dataplane.tail.*
      Path                /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
      parser              docker
      DB                  /var/log/flb_dataplane_tail.db
      Mem_Buf_Limit       50MB
      Skip_Long_Lines     On
      Refresh_Interval    10
      Rotate_Wait         30
      Read_from_Head      true
filter:
  enabled: true
  match: "kube.app.*"
  kubeURL: "https://kubernetes.default.svc.cluster.local:443"
  mergeLog: "On"
  mergeLogKey: "data"
  keepLog: "On"
  k8sLoggingParser: "On"
  k8sLoggingExclude: "Off"
  bufferSize: "32k"
  extraFilters: |
    Kube_Tag_Prefix     kube.app.var.log.containers.
additionalFilters: |
    [FILTER]
        Name                  aws
        Match                 host.*
        imds_version          v2
        az                    true
        ec2_instance_id       true
        ec2_instance_type     true
        private_ip            true
        hostname              true
    
    [FILTER]
        Name                  modify
        Match                 dataplane.systemd.*
        Rename                _HOSTNAME                   hostname
        Rename                _SYSTEMD_UNIT               systemd_unit
        Rename                MESSAGE                     message
        Remove_regex          ^((?!hostname|systemd_unit|message).)*$

    [FILTER]
        Name                  aws
        Match                 dataplane.*
        imds_version          v2
        az                    true
        ec2_instance_id       true
        ec2_instance_type     true
        private_ip            true
        hostname              true
cloudWatchLogs:
  enabled: true
  match: "kube.app.*"
  region: ${region}
  logGroupName: "/aws/eks/fluentbit-cloudwatch/logs"
  logGroupTemplate: /aws/containerinsights/${clusterName}/application/$kubernetes['namespace_name']
  logStreamPrefix: "fluentbit-"
  logStreamTemplate: $kubernetes['pod_name'].$kubernetes['container_name']
  logRetentionDays: 60
additionalOutputs: |
  [OUTPUT]
      Name                cloudwatch_logs
      match               host.*
      region              ${region}
      log_group_name      /aws/containerinsight/${clusterName}/host
      auto_create_group   true
      log_stream_template eks-worker-node-$hostname
      log_stream_prefix   eks
      extra_user_agent    container-insights
      log_retention_days  60
  [OUTPUT]
      Name                cloudwatch_logs
      match               dataplane.*
      region              ${region}
      log_group_name      /aws/containerinsights/${clusterName}/dataplane
      auto_create_group   true
      log_stream_template eks-worker-node-$hostname
      log_stream_prefix   eks
      extra_user_agent    container-insights
      log_retention_days  60

s3:
  enabled: true
  match: "kube.app.*"
  bucket: ${bucket_name} # To change
  region: ${region} # To change
  jsonDateKey: "date"
  jsonDateFormat: "iso8601"
  totalFileSize: "500M"
  uploadChunkSize: "30M"
  uploadTimeout: "15m"
  storeDir: "/tmp/fluent-bit/s3"
  s3KeyFormatTagDelimiters: ._
  storeDirLimitSize: 0
  compression: gzip
  s3KeyFormat: /eks-pod-logs/$TAG[6]/%Y-%m-%d/$TAG[5]-$TAG[6]-$TAG[7]/%Y-%m-%d-%H-%M-%S-$UUID
